from machine import Pin as pin
from utime import sleep, sleep_ms
from machine import Pin
from utime import sleep
led1= Pin(2,Pin.OUT)
led2= Pin(15,Pin.OUT)
led3= Pin(16,Pin.OUT)
led4= Pin(17,Pin.OUT)
led5= Pin(5,Pin.OUT)
led6= Pin(18,Pin.OUT)
led7= Pin(19,Pin.OUT)
led8= Pin(3,Pin.OUT)
led9= Pin(1,Pin.OUT)
led10= Pin(22,Pin.OUT)

pausa=0.2

while True:
  led1.value(1)
  sleep(pausa)
  led1.value(0)
  sleep(pausa)
  led2.value(1)
  sleep(pausa)
  led2.value(0)
  sleep(pausa)
  led3.value(1)
  sleep(pausa)
  led3.value(0)
  sleep(pausa)
  led4.value(1)
  sleep(pausa)
  led4.value(0)
  sleep(pausa)
  led5.value(1)
  sleep(pausa)
  led5.value(0)
  sleep(pausa)
  led6.value(1)
  sleep(pausa)
  led6.value(0)
  sleep(pausa)
  led7.value(1)
  sleep(pausa)
  led7.value(0)
  sleep(pausa)
  led8.value(1)
  sleep(pausa)
  led8.value(0)
  sleep(pausa)
  led9.value(1)
  sleep(pausa)
  led9.value(0)
  sleep(pausa)
  led10.value(1)
  sleep(pausa)
  led10.value(0)
  sleep(pausa)